services:
  db:
    image: postgres:16
    container_name: securetask-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: securetaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
